app/home/forms.py
# _*_ coding: utf-8 _*_
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField
from wtforms.validators import DataRequired, Email, Regexp, EqualTo, ValidationError
from app.models import User

class RegisterForm(FlaskForm):
    """
    用户注册表单
    """
    username = StringField(
        validators=[
            DataRequired("用户名不能为空！"),
        ],
        description="用户名",
        render_kw={
            "placeholder": "请输入用户名！",
        }
    )
    email = StringField(
        validators=[
            DataRequired("邮箱不能为空！"),
            Email("邮箱格式不正确！")
        ],
        description="邮箱",
        render_kw={
            "type": "email",
            "placeholder": "请输入邮箱！",
        }
    )
    pwd = PasswordField(
        validators=[
            DataRequired("密码不能为空！")
        ],
        description="密码",
        render_kw={
            "placeholder": "请输入密码！",
        }
    )
    repwd = PasswordField(
        validators=[
            DataRequired("请输入确认密码！"),
            EqualTo('pwd', message="两次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "placeholder": "请输入确认密码！",
        }
    )
    submit = SubmitField(
        '注册',
        render_kw={
            "class": "btn btn-primary",
        }
    )

    def validate_email(self, field):
        """
        检测注册邮箱是否已经存在
        :param field: 字段名
        """
        email = field.data
        user = User.query.filter_by(email=email).count()
        if user == 1:
            raise ValidationError("邮箱已经存在！")


class LoginForm(FlaskForm):
    """
    登录功能
    """
    email = StringField(
        validators=[
            DataRequired("邮箱不能为空！")
        ],
        description="邮箱",
        render_kw={
            "type"       : "email",
            "placeholder": "请输入邮箱！",
        }
    )
    pwd = PasswordField(
        validators=[
            DataRequired("密码不能为空！")
        ],
        description="密码",
        render_kw={
            "type"       : "password",
            "placeholder": "请输入密码！",
        }
    )
    submit = SubmitField(
        '登录',
        render_kw={
            "class": "btn btn-primary",
        }
    )

class SuggetionForm(FlaskForm):
    """
    意见建议
    """
    name = StringField(
        label="姓名",
        validators=[
            DataRequired("姓名不能为空！")
        ],
        description="姓名",
        render_kw={
            "placeholder": "请输入姓名！",
            "class" : "form-control"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("邮箱不能为空！")
        ],
        description="邮箱",
        render_kw={
            "type"       : "email",
            "placeholder": "请输入邮箱！",
            "class" : "form-control"
        }
    )
    content = TextAreaField(
        label="意见建议",
        validators=[
            DataRequired("内容不能为空！")
        ],
        description="意见建议",
        render_kw={
            "class": "form-control",
            "placeholder": "请输入内容！",
            "rows" : 7
        }
    )
    submit = SubmitField(
        '发送消息',
        render_kw={
            "class": "btn-default btn-cf-submit",
        }
    )

app/home/__init__.py
# _*_ coding:utf-8 _*_

from flask import Blueprint

home = Blueprint("home",__name__)

import app.home.views

app/home/views.py
# _*_ coding: utf-8 _*_
from . import home
from app import db
from app.home.forms import LoginForm,RegisterForm,SuggetionForm
from app.models import User ,Artist,Song,Collect
from flask import render_template, url_for, redirect, flash, session, request,jsonify
from werkzeug.security import generate_password_hash
from functools import wraps

def admin_login(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if session['username'] != 'mr' :
            return redirect(url_for("home.index"))
        return f(*args, **kwargs)
    return decorated_function

def user_login(f):
    """
    登录装饰器
    """
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if "user_id" not in session:
            return "<script>alert('请先登录');history.go(-1)</script>"
        return f(*args, **kwargs)

    return decorated_function

@home.route("/login/", methods=["GET", "POST"])
def login():
    """
    登录
    """
    if request.method == 'POST':
        username = request.form.get("username")
        pwd =  request.form.get("pwd")
        user = User.query.filter_by(username=username).first()    # 获取用户信息
        res = {}
        # 检测用户名
        if not user :
            res['status'] = -1
            res['message'] = '用户名不存在'
            return jsonify(res)
        # 检测密码
        if not user.check_pwd(pwd):     # 调用check_pwd()方法，检测用户名密码是否匹配
            res['status'] = -2
            res['message'] = '用户名和密码不匹配'
            return jsonify(res)
        # 用户名和密码正确，写入session
        session["user_id"] = user.id  # 将user_id写入session, 后面用户判断用户是否登录
        session["username"] = user.username  # 将user_id写入session, 后面用户判断用户是否登录
        res['status'] = 1
        res['message'] = '登录成功'
        return jsonify(res)
    return render_template("home/login.html")

@home.route("/register/", methods=["GET","POST"])
def register():
    """
    注册功能
    """
    if request.method == "POST":   # 提交注册表单
        username = request.form.get("username")
        pwd =  request.form.get("pwd")
        # 判断用户名是否存在
        user = User.query.filter_by(username=username).first()  # 获取用户信息
        if user:
            res = {}
            res['status'] = -2
            res['message'] = '该用户已存在'
            return jsonify(res)
        # 写入到user表
        try:
            # 为User类属性赋值
            user = User(
                username = username,  # 用户名
                pwd = generate_password_hash(pwd),# 对密码加密
            )
            db.session.add(user) # 添加数据
            db.session.commit()  # 提交数据
            res = {}
            res['status'] = 1
            res['message'] = '注册成功'
        except:
            res = {}
            res['status'] = -1
            res['message'] = '注册失败'
        return jsonify(res)
    return render_template("home/register.html")

@home.route("/logout/")
def logout():
    """
    退出登录
    """
    # 重定向到home模块下的登录。
    session.pop("user_id", None)
    session.pop("username", None)
    return redirect(url_for('home.index'))

@home.route("/contentFrame")
def contentFrame():
    """
    主页面
    """
    hot_artist = Artist.query.filter_by(isHot=1).limit(12).all()                              # 获取歌手数据
    hot_song = Song.query.order_by(Song.hits.desc()).limit(10).all()                          # 获取歌曲数据
    return render_template('home/contentFrame.html',hot_artist=hot_artist,hot_song=hot_song) # 渲染模板

@home.route("/")
def index():
    """
    首页
    """
    return render_template('home/index.html') # 渲染模板

@home.route("/artist/<int:id>")
def artist(id=None):
    """
    歌手页
    """
    song = Song.query.join(Artist,Song.singer==Artist.artistName).filter(Artist.id==id).all()
    hot_artist = Artist.query.limit(6).all()
    return render_template('home/artist.html',song=song,hot_artist=hot_artist) # 渲染模板

@home.route("/toplist")
def toplist():
    top_song = Song.query.order_by(Song.hits.desc()).limit(30).all()
    hot_artist = Artist.query.limit(6).all()
    return render_template('home/toplist.html', top_song=top_song, hot_artist=hot_artist)  # 渲染模板

@home.route('/style_list')
def styleList():
    """
    曲风
    """
    type = request.args.get('type',0,type=int)
    page = request.args.get('page',type=int)  # 获取page参数值
    if type:
        page_data = Song.query.filter_by(style=type).order_by(Song.hits.desc()).paginate(page=page, per_page=10)
    else:
        page_data = Song.query.order_by(Song.hits.desc()).paginate(page=page, per_page=10)
    return render_template('home/styleList.html', page_data=page_data,type=type)  # 渲染模板

@home.route('/artist_list')
def artistList():
    '''
    歌手列表
    '''
    type = request.args.get('type',0,type=int)
    page = request.args.get('page',type=int)  # 获取page参数值
    if type:
        page_data = Artist.query.filter_by(style=type).paginate(page=page, per_page=10)
    else:
        page_data = Artist.query.paginate(page=page, per_page=10)
    return render_template('home/artistList.html', page_data=page_data,type=type)  # 渲染模板

@home.route('/search')
def search():
    keyword = request.args.get('keyword') # 获取关键字
    page = request.args.get('page', type=int)  # 获取page参数值
    if keyword :
        keyword = keyword.strip()
        page_data = Song.query.filter(Song.songName.like('%'+keyword+'%')).order_by(Song.hits.desc()).paginate(page=page, per_page=10)
    else:
        page_data = Song.query.order_by(Song.hits.desc()).paginate(page=page, per_page=10)
    return render_template('home/search.html',keyword=keyword,page_data=page_data)


@home.route('/modify_password',methods=['GET','POST'])
def modifyPassword():
    if request.method == 'POST':
        old_pwd =  request.form.get("old_pwd")
        new_pwd =  request.form.get("new_pwd")
        # 检查原始密码是否正确
        user = User.query.filter_by(id=session['user_id']).first()  # 获取用户信息
        res = {}
        if not user.check_pwd(old_pwd):
            res['status'] = -1
            res['message'] = '原始密码错误'
            return jsonify(res)
        # 更改密码
        try:
            user.pwd = generate_password_hash(new_pwd) # 对新密码加密
            db.session.add(user)
            db.session.commit()
            res['status'] = 1
            res['message'] = '密码修改成功'
            return jsonify(res)
        except:
            res['status'] = -2
            res['message'] = '密码修改错误'
            return jsonify(res)
    return render_template("home/modifyPassword.html")


@home.route("/collect")
@user_login
def collect():
    """
    收藏歌曲
    """
    song_id = request.args.get("id", "")            # 接收传递的参数歌曲ID
    user_id   = session['user_id']                  # 获取当前用户的ID
    collect = Collect.query.filter_by(              # 根据用户ID和景区ID判断是否该收藏
        user_id =int(user_id),
        song_id=int(song_id)
    ).count()
    res = {}
    # 已收藏
    if collect == 1:
        res['status'] = 0
        res['message'] = '已经收藏'
    # 未收藏进行收藏
    if collect == 0:
        collect = Collect(
            user_id =int(user_id),
            song_id=int(song_id)
        )
        db.session.add(collect)  # 添加数据
        db.session.commit()      # 提交数据
        res['status'] = 1
        res['message'] = '收藏成功'
    return jsonify(res)     # 返回json数据

@home.route("/collect_list")
@user_login
def collectList():
    page = request.args.get('page',type=int)  # 获取page参数值
    page_data = Collect.query.paginate(page=page, per_page=10)
    return render_template('home/collectList.html',page_data=page_data)


@home.route("/manage_artist_list")
@admin_login
def manageArtist():
    '''
    歌手管理
    '''
    page = request.args.get('page',type=int)  # 获取page参数值
    page_data = Artist.query.paginate(page=page, per_page=10)
    return render_template('home/manageArtist.html', page_data=page_data)


@home.route("/manage_artist_add", methods=["GET","POST"])
@admin_login
def manageArtistAdd():
    '''
    新增歌手
    '''
    if request.method == "POST":   # 提交注册表单
        artistName = request.form.get("artistName")
        style =  request.form.get("style")
        imgURL =  request.form.get("imgURL")
        isHot =  request.form.get("isHot")
        # 判断歌手是否存在
        artist = Artist.query.filter_by(artistName=artistName).first()  # 获取用户信息
        if artist:
            res = {}
            res['status'] = -2
            res['message'] = '该歌手已存在'
            return jsonify(res)
        # 写入到Artist表
        try:
            # 为Artist类属性赋值
            artist = Artist(
                artistName = artistName,
                style  = int(style),
                imgURL = imgURL,
                isHot  = int(isHot)
            )
            db.session.add(artist) # 添加数据
            db.session.commit()    # 提交数据
            res = {}
            res['status'] = 1
            res['message'] = '添加成功'
        except:
            res = {}
            res['status'] = -1
            res['message'] = '添加失败'
        return jsonify(res)
    return render_template('home/manageArtistAdd.html')

@home.route("/manage_artist_edit", methods=["GET","POST"])
@admin_login
def manageArtistEdit():
    '''
    编辑歌手
    '''
    id = request.values['id']      # POST和GET提交都可以获取ID
    artist = Artist.query.filter_by(id=id).first()  # 获取用户信息
    if request.method == "POST":   # 提交注册表单
        # 更改Artist表
        artistName = request.form.get("artistName")
        style = request.form.get("style")
        imgURL = request.form.get("imgURL")
        isHot = request.form.get("isHot")
        try:
            artist.artistName = artistName
            artist.style = int(style)
            artist.imgURL = imgURL
            artist.isHot = int(isHot)
            db.session.add(artist) # 添加数据
            db.session.commit()    # 提交数据
            res = {}
            res['status'] = 1
            res['message'] = '保存成功'
        except :
            res = {}
            res['status'] = -1
            res['message'] = '保存失败'
        return jsonify(res)
    return render_template('home/manageArtistEdit.html',artist=artist)

@home.route("/manage_artist_del")
@admin_login
def manageArtistDel():

app/templates/home/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf8">
    <title>甜橙云音乐</title>
    <link href="{{ url_for('static',filename='css/core.css')}}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/pt_frame.css')}}" rel="stylesheet">
	<link href="{{ url_for('static',filename='js/toolTip/tooltip.css')}}" rel="stylesheet">
	<script type="text/javascript" src="{{url_for('static',filename='js/toolTip/tooltip.js')}}"></script>
	 <script type="text/javascript" src="{{url_for('static',filename='js/jquery-2.2.0.min.js')}}"></script>
    <style>html, body {
        overflow: hidden;
    }</style>
    <script>if (top != self)top.location = self.location;</script>
</head>
<body class="auto-1469062573613-parent auto-1469062573612-parent">


<div id="g-topbar" class="g-topbar">
    <div class="m-top">
        <div class="wrap">
            <h1 class="logo"><a hidefocus="true" target="contentFrame" href="{{url_for('home.index')}}">甜橙云音乐</a></h1>
            <ul class="m-nav j-tflag">
                <li class="fst">
                    <span><a hidefocus="true" target="contentFrame" href="{{url_for('home.search')}}" data-module="discover" class="z-slt"><em>发现音乐</em></a></span>
                </li>
                <li>
                    <span><a target="contentFrame" href="{{url_for('home.collectList')}}"><em>我的音乐</em><sub class="cor">&nbsp;</sub></a></span>
                </li>
            </ul>
			{% if session['username'] %}
            <div class="m-tophead f-pr j-tflag" >
				<a onmouseover="tooltip.pop(this, '#textContent',{position:1, offsetX:0,  effect:'slide'})"  class="tooltip" style="color:#1C2021">您好，{{ session['username']}}</a>
            </div>
			<div style="display: none">
				<div id="textContent" style="width: 75px; height: 45px;color:black">
					{% if session['username'] == 'mr' %}
					<a target="contentFrame" href="{{url_for('home.manageArtist')}}">后台管理</a>
					{% else %}
					<a target="contentFrame" href="{{url_for('home.modifyPassword')}}">修改密码</a>
					{% endif %}
					<br />
					<a id="blogUrl" href="{{url_for('home.logout')}}">退出</a>
				</div>
			</div>
			{% else %}
			<div class="m-tophead f-pr j-tflag">
				<a id="login" class="name f-thide f-fl f-tdn" style="color:#1C2021">登录</a>
				<a id="register" class="name f-thide f-fl f-tdn" style="color:#1C2021">注册</a>
			</div>
			{% endif %}
		</div>
    </div>
    <div class="m-subnav m-subnav-up f-pr j-tflag f-hide">
        <div class="shadow">&nbsp;</div>
    </div>
    <div id="g_nav2" class="m-subnav j-tflag">
        <div class="wrap f-pr">
            <ul class="nav">
                <li><a hidefocus="true" target="contentFrame" href="{{url_for('home.index')}}" data-module="discover"
                       class="z-slt menuTab"><em>推荐</em></a></li>
                <li><a hidefocus="true" target="contentFrame" href="{{url_for('home.toplist')}}" data-module="toplist"
                       class="menuTab"><em>排行榜</em></a></li>
                <li><a hidefocus="true" target="contentFrame" href="{{url_for('home.styleList')}}" data-module="playlist"
					   class="menuTab"><em>曲风</em></a>
                </li>
                <li><a hidefocus="true" target="contentFrame" href="{{url_for('home.artistList')}}" data-module="artist"
                       class="menuTab"><em>歌手</em></a>
				</li>
            </ul>
        </div>
    </div>
</div>
<script>
$(".menuTab").bind("click", function(obj){
	$('.menuTab').removeClass("z-slt");
	obj.currentTarget.className='z-slt menuTab';
});
</script>
<iframe name="contentFrame" id="g_iframe" class="g-iframe" scrolling="auto" frameborder="0"
        src="{{ url_for('home.contentFrame') }}">
</iframe>

<link href="{{url_for('static',filename='css/jplayer.blue.monday.min.css')}}" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="{{url_for('static',filename='js/jplayer/jquery.jplayer.min.js')}}"></script>
<script>
// 定义播放音乐的方法
function playMusic(name, id) {
   addMyList()											// 调用添加播放次数方法
   $("#jquery_jplayer").jPlayer( "destroy" );         	// 销毁正在播放的音乐
   $("#jquery_jplayer").jPlayer({						// 播放音乐
		ready: function(event) {						// 准备音频
			$(this).jPlayer("setMedia", {
				title: name,							// 设置音乐标题
				mp3: "static/images/song/53.mp3"		// 设置播放音乐
			}).jPlayer( "play" );						// 开始播放
		},
		swfPath: "dist/jplayer/jquery.jplayer.swf",     // IE8下的兼容播放
		supplied: "mp3",								// 音乐格式为mp3
		wmode: "window",								// 播放模式“window”
		useStateClassSkin: true,						// 设置默认样式
		autoBlur: false,								// 不支持模糊
		smoothPlayBar: true,							// 支持图标
		keyEnabled: true,								// 支持键盘
		remainingDuration: true,						// 支持动画
		toggleDuration: true 							// 支持进度条
	});
}

// 添加播放次数
function addMyList(id){
	$.ajax({
		url: "{{url_for('home.addHit')}}",		// 提交地址
		type: "get",							// 提交类型
		data: {id: id},							// 提交数据
		success: function(res) {				// 回调函数
			console.log(res.message)
		}
	});
}

// 添加收藏
function addShow(id){
	var username= "{{session['username']}}";
	if(username=="null" || username==""){
		layer.msg("收藏请先登录!",{icon:2,time:1000});
		return;
	}
	$.ajax({
		url: "{{url_for('home.collect')}}",
		type: "get",
		data: {
			id: id
		},
		success: function(res){
			if(res.status==1){
				layer.msg(res.message,{icon:1})
			}else{
				layer.msg(res.message,{icon:2})
			}
        }
     });
}
</script>
		<div id="demo" style="z-index: 999; position: fixed;right:0;left:0;bottom:0;width:100%;">
			<div id="jquery_jplayer" class="jp-jplayer">
			</div>
			<div id="jp_container_1" class="jp-audio" role="application"
				aria-label="media player">
				<div class="jp-type-single">
					<div class="jp-details">
						<div class="jp-title" aria-label="title">
							暂无播放音乐
						</div>
					</div>
					<div class="jp-gui jp-interface" style="margin-left:30% " >
						<div class="jp-controls">
							<button class="jp-play" role="button" tabindex="0">
								play
							</button>
						</div>
						<div class="jp-progress">
							<div class="jp-seek-bar">
								<div class="jp-play-bar"></div>
							</div>
						</div>
						<div class="jp-volume-controls">
							<button class="jp-mute" role="button" tabindex="0">
								mute
							</button>
							<button class="jp-volume-max" role="button" tabindex="0">
								max volume
							</button>
							<div class="jp-volume-bar">
								<div class="jp-volume-bar-value"></div>
							</div>
							<div class="jp-duration" role="timer" aria-label="duration">
								&nbsp;
							</div>
							<div class="jp-time-holder">
								<div class="jp-duration" role="timer" aria-label="duration">
									&nbsp;
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>

<script type="text/javascript" src="{{url_for('static',filename='js/layer/layer.js')}}"></script>
<script>
// 登录弹窗
$("#login").click(function () {
	layer.open({
	  type: 2,
	  title: '登录',
	  shadeClose: true,
	  shade: 0.4,
	  area: ['700px', '550px'],
	  content: ['/login','no'] //iframe的url
	});
});
// 注册弹窗
$("#register").click(function () {
	layer.open({
	  type: 2,
	  title: '注册',
	  shadeClose: true,
	  shade: 0.4,
	  area: ['700px', '550px'],
	  content: ['/register','no'] //iframe的url
	});
})
</script>
</body>
</html>

app/templates/home/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{{ url_for('static',filename='css/core.css')}}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/pt_frame.css')}}" rel="stylesheet">
    <link href="{{ url_for('static',filename='css/login.css')}}" rel="stylesheet">
     <script type="text/javascript" src="{{url_for('static',filename='js/jquery-2.2.0.min.js')}}"></script>
     <script type="text/javascript" src="{{url_for('static',filename='js/layer/layer.js')}}"></script>
</head>
<body>
<div id="loginHtml">
<div class="left"></div>
<div class="right">
    <div class="respond">
        <form  id="commentform"  onsubmit="return false">
            <div class="comment-login"></div>
            <div class="comment-login" style="font-size:16px;margin-top:-40px">
            <ul style="margin-top:100px">
            <li class="form-inline">
            <label><strong>用户名：</strong></label>
            <input type="text" name="username" id="username" value="" tabindex="1" aria-required="true">
            </li>
            <li class="form-inline">
            <label><strong>密&nbsp&nbsp&nbsp&nbsp码：</strong></label>
            <input type="password" name="pwd" id="pwd" value="" tabindex="2" aria-required="true">
            </li>
            </ul>
            </div>
            <div class="comment-login">
                <input name="submit" type="submit" id="login"  class="submitButton" tabindex="5"  value="登录">
            </div>
        </form>
    </div>
</div>
</div>
<script>
    $('#login').click(function(){
        var username = $('#username').val()
        var pwd = $('#pwd').val()
        if(username == ''){
            layer.msg('请输入用户名',{icon:2,time:1000});
            return false;
        }
         if(pwd == ''){
            layer.msg('请输入密码',{icon:2,time:1000});
            return false;
         }
        $.ajax({                                    // 使用Ajax异步提交
            url: "{{ url_for('home.login') }}",     // 提交到的URL
            type: "POST",                            // 提交方式为GET
            data:{username: username,pwd:pwd},            // 传递参数
            dataType: "json",                       // 数据类型为json
            success: function (res) {               // 操作成功后执行逻辑
                if (res.status == 1) {
                    layer.msg(res.message,{icon:1,time:1000},function(){
                    window.parent.location.reload();                        // 从新加载父页面
                    var index = parent.layer.getFrameIndex(window.name);    // 获取当frame标识
                    parent.layer.close(index);                              // 关闭当前页
                    });
                } else {
                    layer.msg(res.message,{icon:2,time:2000});   // 提示已收藏
                }
            }
        })
    })
</script>
</body>
</html>

app/templates/home/manageArtist.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf8">
        <title>甜橙云音乐</title>
        <link href="{{ url_for('static',filename='css/pt_discover_index.css')}}" type="text/css" rel="stylesheet">
        <link href="{{ url_for('static',filename='css/pt_frame.css')}}" type="text/css" rel="stylesheet">
        <script type="text/javascript" src="{{url_for('static',filename='js/jquery-2.2.0.min.js')}}"></script>
        <script type="text/javascript" src="{{url_for('static',filename='js/layer/layer.js')}}"></script>
    </head>
    <body style="background: url('../../static/image/bg.jpg') repeat-y 100% 100%;">
        <div data-module="" data-sub="" id="g_top" class="m-top">
            &nbsp;
        </div>
        <div id="g_nav" class="m-subnav m-subnav-up f-pr">
            <div class="shadow">
                &nbsp;
            </div>
        </div>
        <div class="g-bd" style="margin-top:50px">
            <div class="g-wrap" id="baseBox">
                <div class="u-title u-title-2 f-cb">
                    <h3>
                        <span class="f-ff2">后台管理</span>
                    </h3>
                </div>
                <ul class="m-tabs f-cb">
                    <li class="fst">
                        <a href="{{url_for('home.manageArtist')}}" class="z-slt"><em>歌手</em> </a>
                    </li>
                    <li>
                        <a href="{{url_for('home.manageSong')}}"><em>歌曲</em> </a>
                    </li>
                </ul>
                <div class="g-wrap p-prf">
                    <div class="n-bind f-cb j-flag">
                        <p class="delete">
                            <a target="contentFrame" href="{{url_for('home.manageArtistAdd')}}" class="btn"><i>新增歌手</i>
                            </a>
                        </p>
                    </div>
                    <div class="u-title u-title-1 f-cb m-record-title" id="rHeader">
                        <h3>
                            <span class="f-ff2 s-fc3">歌手列表</span>
                        </h3>
                    </div>
                    <div id="m-record" data-uid="3514008" data-songs="1316"
                        class="m-record">
                        <div id="auto-id-oXK37yPmGlBEcCTf">
                            <div class="j-flag" id="auto-id-42i2wAet2Pki6UW6">
                                <table class="m-table m-table-rank">
                                    <thead>
                                        <tr>

                                            <th>
                                                <div class="wp">
                                                    歌手
                                                </div>
                                            </th>
                                            <th class="w3">
                                                <div class="wp">
                                                    分类
                                                </div>
                                            </th>
                                            <th class="w3">
                                                <div class="wp">
                                                    是否热门
                                                </div>
                                            </th>
                                            <th class="w3">
                                                <div class="wp">
                                                    操作
                                                </div>
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for artist in page_data.items %}
                                        <tr>
                                            <td class="rank">
                                                {{artist.artistName}}
                                            </td>
                                            <td class=" s-fc3">
                                                {% if artist.style == 1 %}
                                                华语歌手
                                                {% elif artist.style == 2%}
                                                欧美歌手
                                                {% elif artist.style == 3%}
                                                日语歌手
                                                {% elif artist.style == 4%}
                                                韩语歌手
                                                {% elif artist.style == 5%}
                                                其他歌手
                                                {% endif %}
                                            </td>
                                            <td class=" s-fc3">
                                            {% if artist.isHot == 1%}
                                                是
                                            {% else %}
                                                否
                                            {% endif %}
                                            </td>
                                            <td class="">
                                                <a href="{{url_for('home.manageArtistEdit',id=artist.id)}}">修改</a>
                                                <a href="javascript:;" class="del" value="{{artist.id}}">删除</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                    <tr>
                                        <td height="24" align="right">
                                            当前页数：[{{page_data.page}}/{{page_data.pages}}]&nbsp;
                                            <a href="{{ url_for('home.manageArtist',page=1) }}">第一页</a>
                                                {% if page_data.has_prev %}
                                                  <a href="{{ url_for('home.manageArtist',page=page_data.prev_num) }}">上一页</a>
                                                {% endif %}
                                                {% if page_data.has_next %}
                                            　     <a href="{{ url_for('home.manageArtist',page=page_data.next_num) }}">下一页</a>
                                                {% endif %}　
                                            <a href="{{ url_for('home.manageArtist',page=page_data.pages) }}">最后一页&nbsp;</a>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <div class="j-flag"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</script>
    <script>
        $('.del').click(function(){
            id = $(this).attr('value');
            layer.confirm('确认删除',function(){
                $.ajax({                                    // 使用Ajax异步提交
                    url: "{{ url_for('home.manageArtistDel') }}",   // 提交到的URL
                    type: "GET",                            // 提交方式为GET
                    data:{id:id},// 传递参数
                    dataType: "json",                       // 数据类型为json
                    success: function (res) {               // 操作成功后执行逻辑
                        if (res.status == 1) {
                            layer.msg(res.message,{icon:1,time:2000},function(){
                                window.location.href='/manage_artist_list';
                            });
                        } else {
                            layer.msg(res.message,{icon:2,time:2000});   // 提示失败
                        }
                    }
                })
            })
        })
    </script>
    </body>
</html>